version: '2'

services:

  app:
    build:
      context: ./
      dockerfile: dockerfile.app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env

  web:
    image: nginx:1.15.7
    working_dir: /var/www
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    ports:
      - 8080:80

  database:
    image: mariadb:10.2.17
    volumes:
      - ./docker/dbdata:/var/lib/mysql:rw
    env_file:
      - .env-mariadb
    ports:
      - '6604:3306'
